AMPLITUDE = 300
SPEED = 100
LANG = "english-us"
MALES = ["+m"+str(i) for i in range(1,8)]
FEMALES = ["+f"+str(i) for i in range(1,5)]
PROMPT = "Say: "
EXIT_LIST = ["bye", "bye bye", "later", "goodbye", "so long"]
NO_TEXT_MESSAGE = "You didn't type anything for me to say. What are you thinking Broh!"
GOODBYE_MESSAGE = "Later broh"